//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class answer
{
    public string Id { get; set; }
    public string Text { get; set; }
    public bool IsAnswer { get; set; }
    public string QuestionId { get; set; }

    public virtual question question { get; set; }
}

public partial class coursesection
{
    public string Id { get; set; }
    public string Header { get; set; }
    public Nullable<int> SectionOrder { get; set; }
    public Nullable<bool> Quiz { get; set; }
    public string ProjectId { get; set; }

    public virtual exam exam { get; set; }
}

public partial class exam
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public exam()
    {
        this.questions = new HashSet<question>();
    }

    public string Id { get; set; }
    public string Header { get; set; }
    public int TotalPoints { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<question> questions { get; set; }
    public virtual coursesection coursesection { get; set; }
}

public partial class question
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public question()
    {
        this.answers = new HashSet<answer>();
    }

    public string Id { get; set; }
    public string Text { get; set; }
    public string ExamId { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<answer> answers { get; set; }
    public virtual exam exam { get; set; }
}
